#!/usr/bin/env bash
set -Eeuo pipefail
: "${EXPECTED_CANDIDATE_HASH:?Exact tested candidate required}"
: "${LEGO_RELEASE_AUTHORIZATION_OVERRIDE:?v4 release authorization required}"
: "${LEGO_TRADING_WINDOW_END_OVERRIDE:?New explicit approval expiry required}"
export WEBULL_ENV_OVERRIDE=UAT LEGO_MODE_OVERRIDE=trade LEGO_ACTIVE_OVERRIDE=true
export LEGO_SYMBOL_OVERRIDE=UBER LEGO_FIX_C_OVERRIDE=10000 LEGO_DIFF_OVERRIDE=25
export LEGO_ALLOW_FRACTIONAL_OVERRIDE=true LEGO_SESSION_KEY_MODE_OVERRIDE=market_day
export LEGO_STALE_ORDER_ACTION_OVERRIDE=cancel LEGO_STALE_ORDER_SECONDS_OVERRIDE=300
export LEGO_CANCEL_CONFIRM_GRACE_SECONDS_OVERRIDE=120 LEGO_MAX_SESSION_ORDERS_OVERRIDE=30
export LEGO_MAX_ORDER_QUANTITY_OVERRIDE=1000 LEGO_MAX_ORDER_NOTIONAL_USD_OVERRIDE=36000
export LEGO_SCHEDULE_OVERRIDE='* * * * *'
exec bash deploy/cloudshell-all-in-one.sh
